ALTER TABLE admin_permissions 
ADD COLUMN IF NOT EXISTS can_create_orders BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS order_daily_limit INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS order_current_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS order_last_reset DATE DEFAULT CURRENT_DATE,
ADD COLUMN IF NOT EXISTS can_edit_orders BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS order_edit_daily_limit INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS order_edit_current_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS order_edit_last_reset DATE DEFAULT CURRENT_DATE,
ADD COLUMN IF NOT EXISTS can_edit_all_orders BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS can_delete_orders BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS can_delete_all_orders BOOLEAN DEFAULT FALSE;